server:
  port: 7000

spring:
  application:
    name: zuul-service

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka


zuul:
  routes:
    item-service: /item/**
    upload-service: /upload/**
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 3000
  prefix: /api

#降级处理超时时间设置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeout-in-milliseconds: 3000
